name: Generic Deploy Frontend

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      SSH_CONFIG_JSON:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout main code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Build Frontend with linked library
      - name: Set variables
        id: vars
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
          TIMESTAMP=$(date +'%Y%m%d')
          echo "FRONTEND_VERSION=$TIMESTAMP.$SHORT_SHA.${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "TARGET_DIR=/home/www/${{ inputs.service_name }}" >> $GITHUB_OUTPUT

      - name: Build Frontend
        run: |
          npm ci
          FRONTEND_VERSION=${{ steps.vars.outputs.FRONTEND_VERSION }} npm run build

      # Rest of your deployment steps

      - name: Prepare VPS
        id: prepare
        uses: appleboy/ssh-action@master
        with:
          host: ${{ fromJSON(secrets.SSH_CONFIG_JSON).host }}
          port: ${{ fromJSON(secrets.SSH_CONFIG_JSON).port }}
          username: ${{ fromJSON(secrets.SSH_CONFIG_JSON).user }}
          key: ${{ fromJSON(secrets.SSH_CONFIG_JSON).key }}
          script: |
            mkdir -p ${{ steps.vars.outputs.TARGET_DIR }}
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            BACKUP_DIR=/home/www-backup/${{ inputs.service_name }}_$TIMESTAMP
            mkdir -p $BACKUP_DIR
            cp -R ${{ steps.vars.outputs.TARGET_DIR }}/* $BACKUP_DIR
            rm -rf ${{ steps.vars.outputs.TARGET_DIR }}/*

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ fromJSON(secrets.SSH_CONFIG_JSON).host }}
          port: ${{ fromJSON(secrets.SSH_CONFIG_JSON).port }}
          username: ${{ fromJSON(secrets.SSH_CONFIG_JSON).user }}
          key: ${{ fromJSON(secrets.SSH_CONFIG_JSON).key }}
          source: "dist/*"
          target: ${{ steps.vars.outputs.TARGET_DIR }}
          strip_components: 1
